### ISSUE TITLE
npm install -q

### ISSUE THREAD

**Issue by wotmshuaisi** [tbranyen/github-viewer#33]
npm WARN lifecycle github-viewer@1.0.0~postinstall: cannot run in wd %s %s (wd=%s) github-viewer@1.0.0 bower install -s /root/github-viewer
npm WARN github-viewer@1.0.0 requires a peer of generator-bbb@\* but none was installed.
npm WARN github-viewer@1.0.0 requires a peer of bower@\* but none was installed.
npm WARN github-viewer@1.0.0 requires a peer of grunt-cli@\* but none was installed.
npm WARN bbb@0.2.0 requires a peer of grunt-bbb-requirejs@\* but none was installed.
npm WARN bbb@0.2.0 requires a peer of grunt-bbb-server@\* but none was installed.
npm WARN bbb@0.2.0 requires a peer of grunt-bbb-styles@\* but none was installed.
npm WARN grunt-karma@0.8.3 requires a peer of karma@~0.12.0 but none was installed.
npm WARN karma-coverage@0.1.5 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-jasmine@0.1.6 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-mocha@0.1.10 requires a peer of karma@>=0.12.8 but none was installed.
npm WARN karma-mocha@0.1.10 requires a peer of mocha@\* but none was installed.
npm WARN karma-phantomjs-launcher@0.1.4 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-qunit@0.1.8 requires a peer of qunitjs@^1.14.0 but none was installed.
npm WARN github-viewer@1.0.0 No repository field.
npm WARN github-viewer@1.0.0 No license field.

**Comment by leodutra** [comment]
Same. Can't run.
